name: vote69-ireadelection
region: sgp
services:
  - name: web
    github:
      repo: leonaruebet/vote69-ireadelection
      branch: main
      deploy_on_push: true
    source_dir: /app
    environment_slug: node-js
    build_command: npm ci && npm run build
    run_command: npm run start
    http_port: 3000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_AND_BUILD_TIME
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
        scope: RUN_AND_BUILD_TIME
